# Generated by Django 4.2.7 on 2026-02-01 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_views', models.IntegerField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pastes',
                'indexes': [models.Index(fields=['expires_at'], name='pastes_expires_799a03_idx')],
            },
        ),
    ]
